export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  changes: {
    type: 'new' | 'fix' | 'improve';
    text: string;
  }[];
}

export const changelog: ChangelogEntry[] = [
  {
    version: '2.11.0',
    date: '18. 9. 2026',
    title: 'Odběr novinek e-mailem',
    changes: [
      { type: 'new', text: 'Odběr novinek e-mailem: s předstihem pošleme termíny přijímacího řízení a zprávu, když na web přibudou nová data; formulář je na titulní stránce a dalších místech webu' },
      { type: 'new', text: 'Odběr začíná až potvrzením odkazem v e-mailu, odhlášení je jedním kliknutím v každé zprávě; v e-mailech nic neměříme' },
      { type: 'new', text: 'Administrace ukazuje přehled odběru: počet odběratelů, nové za 7 a 30 dní, čekající potvrzení, stav fronty a odkud se lidé přihlašují' },
      { type: 'fix', text: 'Potvrzovací e-mail se posílá na adresu, se kterou se člověk právě přihlásil; odesílač dříve mohl z fronty vzít cizí čekající položku a potvrzení nedorazilo' },
    ],
  },
  {
    version: '2.10.2',
    date: '14. 9. 2026',
    title: 'Srozumitelnější maturita na stránce školy',
    changes: [
      { type: 'improve', text: 'Maturita na stránce školy začíná jednou větou: kolik maturantů maturitu udělalo a jak často byli v češtině nad středem podobných škol' },
      { type: 'improve', text: 'Přehledná tabulka po oborech a výsledky slovy „lépe než 91 ze 100 maturantů“ místo percentilů; podrobnosti po letech na rozkliknutí' },
      { type: 'fix', text: 'Úspěšnost u maturity se uvádí z přihlášených maturantů, stejně jako ji počítá CERMAT; dříve stál vedle podílu počet z konajících' },
      { type: 'fix', text: 'Srovnání s podobnými školami je celé v jedné veličině, v podílu bodů z testu: střed, výsledek školy i graf. Percentil zůstal jen jako srovnání s maturanty v celé zemi' },
    ],
  },
  {
    version: '2.10.1',
    date: '14. 9. 2026',
    title: 'Druhé kolo na nových stránkách',
    changes: [
      { type: 'improve', text: 'Stránka oboru ukazuje u 2. kola, kolik uchazečů se nevešlo, zda se nikdo nepřihlásil, proč škola nepřijala všechny a nejnižší výsledek přijatých, s předchozím rokem' },
      { type: 'new', text: 'Stránka školy u každého oboru uvádí, zda škola vypsala 2. kolo a kolik přijala' },
      { type: 'new', text: 'Otevřená data školy obsahují údaje o 2. kole u každého oboru' },
      { type: 'fix', text: 'Obory bez zaměření, které přibyly v nabídce 2026, mají vlastní stránku; odkaz dříve vedl na přehled školy' },
    ],
  },
  {
    version: '2.10.0',
    date: '14. 9. 2026',
    title: 'Nová stránka školy',
    changes: [
      { type: 'new', text: 'Stránka školy odpovídá na pět otázek: co tu lze studovat, jak dobrá škola je, jaká je, kde je a jaké školy jsou v okolí' },
      { type: 'new', text: 'U každého oboru obtížnost přijetí slovy, přihlášky a průměrné body přijatých; uložení mezi zvažované přímo z přehledu školy' },
      { type: 'new', text: 'Kam se hlásí stejní uchazeči: školy, které uchazeči oborů školy měli na přihlášce zároveň, s obtížností přijetí a vzdáleností' },
      { type: 'new', text: 'Schéma okolí školy se školami podle směru a vzdálenosti vzdušnou čarou' },
      { type: 'new', text: 'Údaje, které vyplnila škola v portálu, jsou označené „Potvrdila škola“ a patří k otázkám, na které odpovídají; odkaz „Editujte: pro vedení školy“' },
      { type: 'improve', text: 'Každý údaj nese původ: oficiální data, údaj školy, text školy, automatické shrnutí inspekce, nebo starší profil InspIS' },
      { type: 'improve', text: 'Portál pro školy má nová nepovinná pole stravování a kontakt na výchovného poradce' },
      { type: 'improve', text: 'Maturitní výsledky společné části za roky 2023–2026 na stránce školy, srovnané se školami stejné skupiny oborů' },
      { type: 'fix', text: 'Otevřená data školy v Markdownu a JSON ukazují stejný ročník a obsah jako stránka školy místo dat z roku 2025' },
      { type: 'fix', text: 'Opravena předložka před čísly podle výslovnosti: „ze 44“, „ze 4 let“, „z 55“' },
    ],
  },
  {
    version: '2.9.0',
    date: '14. 9. 2026',
    title: 'Nová stránka oboru: jak těžké je se dostat',
    changes: [
      { type: 'new', text: 'Stránka oboru odpovídá na tři otázky: jak těžké je se sem dostat, co vám pomůže a jak se tu studuje' },
      { type: 'new', text: 'Obtížnost přijetí slovy (velmi těžké, těžké, středně těžké) podle toho, kolik soutěžících uchazečů se v 1. kole dostalo, vždy se srovnáním s předchozím rokem' },
      { type: 'new', text: 'Vysvětlení, kolik uchazečů nedosáhlo požadavku školy, a když to z výsledků jde poznat, jaké minimum bodů škola vyžadovala' },
      { type: 'new', text: 'Obory, které měli uchazeči na přihlášce výš a níž, s obtížností přijetí na ně, a kolik uchazečů se v 1. kole nedostalo nikam' },
      { type: 'new', text: 'Pořadí v kraji podle zájmu a podle výsledků přijatých mezi obory stejného typu a délky; Praha samostatně' },
      { type: 'new', text: 'Tlačítko „Uložit mezi zvažované“ sdílí výběr se simulátorem' },
      { type: 'improve', text: 'Grafy po letech, rozpad všech přihlášek, bodová pásma a tabulka údajů v číslech na rozkliknutí; čitelné i na mobilu' },
      { type: 'improve', text: 'Shrnutí inspekce na stránce oboru: co chválí, na co si dát pozor, podpora žáků a otázky na den otevřených dveří' },
      { type: 'fix', text: 'Stránka školy už nesčítá přihlášky a přijaté přes různé obory do zavádějících poměrů' },
    ],
  },
  {
    version: '2.8.0',
    date: '13. 9. 2026',
    title: 'Portál pro školy a čerstvější data inspekcí',
    changes: [
      { type: 'new', text: 'Portál pro školy: škola si sama doplní a upraví svůj profil — zaměření, aktuality i kontakty; přístup přes jednorázový kód nebo odkaz zaslaný na rejstříkový e-mail' },
      { type: 'new', text: 'Příspěvky škol prochází moderací a zobrazují se na stránce školy' },
      { type: 'improve', text: 'Sekce „Jak to dopadlo loni“ počítá z finální revize dat 2025, která zohledňuje i vzdání se přijetí; počty se u části oborů mírně posunuly' },
      { type: 'improve', text: 'Inspekce ČŠI aktualizovány na snímek ze 7. 9. 2026' },
    ],
  },
  {
    version: '2.7.0',
    date: '13. 9. 2026',
    title: 'Ročník 2026 v katalogu a jak dopadli loňští uchazeči',
    changes: [
      { type: 'new', text: 'Nová sekce „Jak to dopadlo loni“ na stránce oboru: pod kolika body se v 1. kole 2025 nedostal nikdo, nad kolika se dostali všichni a kolik uchazečů uspělo v rozmezí mezi tím' },
      { type: 'new', text: 'U každého oboru věta o tom, zda o přijetí rozhodoval hlavně výsledek jednotné zkoušky, nebo i další kritéria školy; u oborů s talentovou zkouškou místo ní upozornění, že rozhoduje i talentová zkouška' },
      { type: 'improve', text: 'Upozornění u nabídek, kde údaje platí za celý obor školy nebo kde jde o novou nabídku 2026, a vysvětlení, když údaje za loňsko chybí' },
      { type: 'new', text: 'Podrobné rozdělení přijatých podle výsledku zkoušky na rozkliknutí, jen u oborů, kde se někdo nevešel kvůli kapacitě' },
      { type: 'new', text: 'Nový blok „Druhé kolo“ na stránce oboru: kolik míst škola ve 2. kole vypsala, kolik přišlo přihlášek a kolik uchazečů přijala, a upozornění, když se obor v 1. kole nenaplnil a 2. kolo přesto nebylo' },
      { type: 'new', text: 'Ročník 2026 přidán do katalogu se stabilními adresami nabídek; žádná stránka z roku 2025 nezanikla' },
      { type: 'new', text: 'Statistiky oboru ukazují data 1. kola 2026: přihlášky podle priority, průměrné výsledky přijatých a srovnání ročníků 2025 a 2026' },
      { type: 'improve', text: 'Přehled oborů na stránce školy přejmenován na „Studijní obory školy“ a uspořádán do přehledných záložek' },
      { type: 'improve', text: 'Web uvádí, kde je návaznost oboru mezi roky nejistá, a nabízí nahlásit správný stav přes GitHub Issues' },
      { type: 'improve', text: 'Simulátor sjednocen s katalogem a pracuje s celou nabídkou 1. kola 2026' },
      { type: 'improve', text: 'Každé číslo na webu má doloženou definici v závazném slovníku ukazatelů, včetně toho, co číslo neříká' },
      { type: 'fix', text: 'Opraveny nadpisy, které označovaly data roku 2026 jako rok 2025' },
      { type: 'fix', text: 'Opravena věta, že CERMAT za rok 2026 nezveřejňuje přijaté podle priority; zveřejňuje' },
      { type: 'fix', text: 'Přegenerována mapa stránek z aktuálního katalogu' },
    ],
  },
  {
    version: '2.6.0',
    date: '11. 9. 2026',
    title: 'Simulátor výběru oboru a kalendář přijímaček 2027',
    changes: [
      { type: 'new', text: 'Kalendář přijímacího řízení 2027 a obnovená data CERMAT (#71)' },
      { type: 'new', text: 'Simulátor výběru oboru s dojezdovou dobou, výsledky uchazečů a důvody nepřijetí' },
      { type: 'new', text: 'Srovnávací tabulka oborů v simulátoru bez omezení počtu vybraných oborů' },
      { type: 'improve', text: 'Výsledky oborů a související nabídky škol zvýrazněny na stránce školy' },
      { type: 'fix', text: 'Z profilu oboru odstraněn index obtížnosti, jehož výpočet se nepodařilo doložit' },
      { type: 'fix', text: 'Odstraněny osobní predikce šancí a neověřená minima bodů z regionálních souhrnů' },
      { type: 'fix', text: 'Rozlišena délka studia ve srovnání oborů a v odkazech z přehledu kraje' },
      { type: 'fix', text: 'Opraveny náhledové obrázky při sdílení (chyba 500 a chybějící české znaky)' },
    ],
  },
  {
    version: '2.5.1',
    date: '5. 6. 2026',
    title: 'Opravy tipů o prioritě a výsledků',
    changes: [
      { type: 'fix', text: 'Opraven zavádějící tip o prioritě: priorita neurčuje šanci na přijetí, jen pořadí nástupu (#70)' },
      { type: 'fix', text: 'Školy ve výsledcích se zobrazují s rozlišujícím názvem, například pražská gymnázia (#69, #63)' },
      { type: 'fix', text: 'Filtry na stránce výsledků se zachovají po návratu z detailu školy (#60)' },
    ],
  },
  {
    version: '2.5.0',
    date: '16. 5. 2026',
    title: 'Výsledky přijímaček 2026 a přehledy měst',
    changes: [
      { type: 'new', text: 'Stránka s výsledky přijímacího řízení 2026 a jejich souhrn na úvodní stránce' },
      { type: 'new', text: 'Výsledky 1. kola 2026 na stránce každé školy' },
      { type: 'new', text: 'Přehledy středních škol pro 20 největších měst' },
      { type: 'fix', text: 'Sjednoceny jednotky výsledků CERMAT; součet češtiny a matematiky se uvádí správně na škále do 200 %' },
      { type: 'fix', text: 'Opraveno školné Rakouského gymnázia (#59)' },
    ],
  },
  {
    version: '2.4.4',
    date: '30. 4. 2026',
    title: 'Opravy kapacit, regionů a vyhledávání',
    changes: [
      { type: 'fix', text: 'Opravena kapacita u 212 škol s více zaměřeními (#55)' },
      { type: 'fix', text: 'Opravena chyba 404 u kraje Hlavní město Praha (#57)' },
      { type: 'fix', text: 'Moje šance fungují i s jedinou vybranou školou (#56)' },
      { type: 'improve', text: 'Vyhledávání v Moje šance podporuje víceslovné dotazy (#50)' },
      { type: 'fix', text: 'Opraveny gramatické chyby „převys“ a „Rychlé fakta“ (#51)' },
    ],
  },
  {
    version: '2.4.3',
    date: '10. 3. 2026',
    title: 'Oprava zobrazení kapacit a oborů na detailu školy',
    changes: [
      { type: 'fix', text: 'Oprava chybného matchování dat 2026 na obory se zaměřeními — školy s více zaměřeními (např. Gymnázium Na Zatlance ALT/VIA) nyní zobrazují správné kapacity pro každé zaměření (#46)' },
      { type: 'fix', text: 'Header statistiky detailu školy nyní primárně zobrazují data 2026 (kapacita, přihlášky) s údaji 2025 v závorce, místo zavádějícího zobrazení loňských dat' },
      { type: 'improve', text: 'Vyhledávání zobrazuje plný název školy (např. "Gymnázium, Na Zatlance") a zaměření u oborů (např. "Gymnázium - ALT") pro lepší rozlišení výsledků' },
      { type: 'improve', text: 'Vyhledávání nyní hledá i v názvu zaměření a plném názvu školy' },
    ],
  },
  {
    version: '2.4.2',
    date: '13. 2. 2026',
    title: 'Opravy nočních spojů, simulátoru a náročnosti přijetí',
    changes: [
      { type: 'fix', text: 'Oprava nočních linek v dopravní dostupnosti — filtrování nočních tramvají (91-99) a autobusů (901-999) + časové okno změněno na 6:30-9:00 pro školní dojíždění (#21)' },
      { type: 'improve', text: 'GitHub Actions pro automatické zpracování issues deaktivovány — issues nyní zpracovány ručně' },
      { type: 'fix', text: 'Simulator zobrazuje jednotlivé obory samostatně — studenti si vybírají obory, ne školy. Každý obor má vlastní kartu s názvem školy, oborem, délkou studia a zaměřením (#22)' },
      { type: 'new', text: 'Vizuální označení oborů s nízkou poptávkou v simulátoru — žlutý badge "⚠️ Nízká poptávka" pro obory s index_poptavky < 1.0' },
      { type: 'improve', text: 'Změna zavádějícího nadpisu "Profil náročnosti školy" na "Náročnost přijetí na školu" — jasné rozlišení obtížnosti přijetí vs. obtížnosti studia (#28)' },
      { type: 'improve', text: 'Rozšířené vysvětlení u percentilů — "V rámci celé ČR" místo "Celková náročnost" pro lepší srozumitelnost' },
    ],
  },
  {
    version: '2.4.1',
    date: '11. 2. 2026',
    title: 'Opravy dopravní dostupnosti a UI patičky',
    changes: [
      { type: 'fix', text: 'Oprava filtrovací podmínky dojezdového času — školy s časem přesně 30 min se nyní zobrazí při limitu 30 min (zaokrouhlování před porovnáním)' },
      { type: 'fix', text: 'Reálnější výpočet pěší vzdálenosti — rychlost 4 km/h + koeficient 1,3× pro reálnou trasu (místo 5 km/h přímá čára)' },
      { type: 'new', text: '"Near miss" počítadlo — zobrazuje počet škol v čase +5 minut pod výsledky s tlačítkem pro rozšíření limitu' },
      { type: 'new', text: 'Logo Hlídače státu (48×48px) přidáno do patičky s odkazem na www.hlidacstatu.cz' },
      { type: 'fix', text: 'Opravena kolize tlačítek — tlačítko "Nahlásit chybu" posunuto vlevo (80px mezera od pravého okraje)' },
      { type: 'improve', text: 'Aktualizovaná dokumentace výpočtu chůze (rychlost 4 km/h, koeficient trasy 1,3×)' },
    ],
  },
  {
    version: '2.4.0',
    date: '10. 2. 2026',
    title: 'AI shrnutí inspekčních zpráv ČŠI na detailu školy',
    changes: [
      { type: 'new', text: 'Kompaktní blok „Co zjistila inspekce" na stránce školy — shrnutí, silné stránky a rizika z AI analýzy inspekční zprávy' },
      { type: 'new', text: 'Samostatná stránka /skola/[slug]/inspekce s podrobným shrnutím všech inspekčních zpráv školy (836 stránek)' },
      { type: 'new', text: 'Zobrazení: shrnutí pro rodiče, silné stránky, rizika, komu škola sedí, otázky na den otevřených dveří, fakta ze zprávy' },
      { type: 'new', text: 'Tlačítko „Co si o škole myslí Školská inspekce?" v hlavičce školy s odkazem na detail inspekce' },
      { type: 'improve', text: 'Nejnovější inspekce vždy rozbalená, starší sbalené v rozbalovacím panelu' },
      { type: 'improve', text: 'Školy bez AI extrakce zobrazí fallback s datem inspekce a odkazem na PDF' },
      { type: 'improve', text: 'AI disclaimer upozorňující na automatické zpracování inspekční zprávy' },
    ],
  },
  {
    version: '2.3.1',
    date: '9. 2. 2026',
    title: 'Aktualizace pokrytí MHD na stránce dostupnosti',
    changes: [
      { type: 'improve', text: 'Sekce „Zobrazit města s MHD daty" aktualizována podle aktuálních dat v transit grafu' },
      { type: 'improve', text: 'Původní fixní výčet měst nahrazen aktuálním výběrem měst s největším pokrytím' },
      { type: 'improve', text: 'Doplněn zdroj jízdních řádů: github.com/tangero/jizdni-rady-czech-republic' },
    ],
  },
  {
    version: '2.3.0',
    date: '8. 2. 2026',
    title: 'Bug report widget, UX dopravních informací a zarovnání tabulek',
    changes: [
      { type: 'new', text: 'Plovoucí tlačítko „Nahlásit chybu" — formulář vytvoří GitHub Issue přímo z webu' },
      { type: 'new', text: 'API endpoint /api/bug-report s rate limitingem (3 req/15 min) a serverovou validací' },
      { type: 'improve', text: 'Dopravní informace v kartách dostupnosti přesunuty do vlastního pruhu přes celou šířku s většími fonty' },
      { type: 'improve', text: 'Zarovnání sloupců tabulky oborů (table-layout: fixed) — hodnoty pod sebou napříč kartami' },
    ],
  },
  {
    version: '2.2.0',
    date: '8. 2. 2026',
    title: 'Redesign dostupnosti: per-oborové detaily a opravy mapování škol',
    changes: [
      { type: 'new', text: 'Kartový layout výsledků dostupnosti — škola + doprava na prvním řádku, obory s detaily na druhém' },
      { type: 'new', text: 'Per-oborové údaje: body min (JPZ), body průměr, index konkurence, kapacita, délka studia u každého oboru' },
      { type: 'new', text: 'Barevné kódování JPZ bodů podle kohort (<30 emerald, 30-49 green, 50-69 amber, 70+ red)' },
      { type: 'new', text: 'InfoTooltip nápověda u sloupců Body min, Body prům a Konkurence' },
      { type: 'new', text: 'Seznam 15 měst s MHD daty (DPP, DPMB, DPO, PMDP, DPMO atd.) v rozbalovacím panelu' },
      { type: 'new', text: 'Upozornění, že pro ostatní obce máme pouze meziměstskou dopravu (autobusy a vlaky)' },
      { type: 'improve', text: 'Geokódování školních adres přes Nominatim — 914 unikátních zastávek místo 389 (Praha: 146 místo 1)' },
      { type: 'improve', text: 'Filtrování nočních linek z GTFS grafu — pouze ranní tripy (5:00–10:00)' },
      { type: 'improve', text: 'Headway výpočet přesunut před agregaci hran, linky bez headway dat se odfiltrují' },
      { type: 'fix', text: 'Oprava city_match chyby: všechny školy v jednom městě mapovány na jednu zastávku (179 pražských škol → Vršovické nám.)' },
      { type: 'fix', text: 'Oprava min_body → jpz_min_actual: použití JPZ bodů (CJ+MA, max 100) místo celkových bodů' },
    ],
  },
  {
    version: '2.1.0',
    date: '7. 2. 2026',
    title: 'Grafická kompatibilita s Hlídačem státu',
    changes: [
      { type: 'new', text: 'Kompletní redesign — grafická kompatibilita s ekosystémem Hlídače státu (hlidacstatu.cz)' },
      { type: 'new', text: 'Nová hlavička: bílý navbar se stínem, modré SVG logo, tmavě modrý vyhledávací panel (#003688)' },
      { type: 'new', text: 'Nová patička: světle šedé pozadí, badge „Projekt Hlídače státu" s odkazem' },
      { type: 'new', text: 'Design analýza Hlídače státu uložena v docs/hlidacstatu-design-analyza.md' },
      { type: 'improve', text: 'Migrace barevné palety z indigo/purple na HŠ modrou (#0074e4) napříč všemi 25 soubory' },
      { type: 'improve', text: 'Font Cabin načítaný přes next/font/google místo systémového fontu' },
      { type: 'improve', text: 'CSS proměnné aktualizovány na HŠ design systém (--color-primary, --color-text atd.)' },
      { type: 'improve', text: 'Jednotný vizuální styl: 4px border-radius, žádné gradienty, čistý flat design' },
      { type: 'improve', text: 'Vylepšený kontrast placeholderu ve vyhledávání' },
    ],
  },
  {
    version: '2.0.0',
    date: '7. 2. 2026',
    title: 'Transfer-aware Dijkstra v2 a rebranding',
    changes: [
      { type: 'new', text: 'Transfer-aware Dijkstra — realistické přepravní časy s přestupními penalizacemi a čekáním na spoj (headway/2)' },
      { type: 'new', text: 'Zobrazení použitých linek (autobus, vlak, metro) u každé dostupné školy' },
      { type: 'new', text: 'Rozpad času na jízdu, čekání a chůzi u každé trasy' },
      { type: 'new', text: 'Počet přestupů jako badge u každé školy' },
      { type: 'new', text: 'Filtr podle typu školy (GY4, GY8, LYC, SOŠ, SOU...)' },
      { type: 'new', text: 'Kompletní seznam oborů/zaměření u každé školy místo jednoho typu' },
      { type: 'new', text: 'Adresa školy v přehledu dostupnosti' },
      { type: 'new', text: 'Panel „Jak to funguje" s návodem a vysvětlením výpočtu' },
      { type: 'new', text: 'Nová SVG favicon — motiv graduační čepice' },
      { type: 'improve', text: 'Přejmenování serveru na „Přijímačky na střední školy"' },
      { type: 'improve', text: 'Menu: „Dojezdovost ČR" → „Do jaké školy dojedete MHD"' },
      { type: 'improve', text: 'Odebrána položka „Školy dostupné MHD" (nahrazena celostátní dojezdovostí)' },
      { type: 'improve', text: 'Trvalý redirect /praha-dostupnost → /dostupnost' },
      { type: 'improve', text: 'Build skript pro graf z GTFS — 35 575 zastávek, 1 431 linek, headway tabulka' },
      { type: 'new', text: 'Vlastní doména prijimackynaskolu.cz' },
      { type: 'improve', text: 'Nový hlavní titulek: „Najdi si svou střední školu a zjisti své šance"' },
      { type: 'improve', text: 'Aktualizace všech kanonických URL, sitemapy a robots.txt na novou doménu' },
    ],
  },
  {
    version: '1.5.2',
    date: '7. 2. 2026',
    title: 'Optimalizace našeptávače zastávek',
    changes: [
      { type: 'improve', text: 'Předpočítaný index pro vyhledávání zastávek — místo 36k normalizací při každém dotazu jen lookup do Map' },
      { type: 'new', text: 'Klávesová navigace v našeptávači (šipky, Enter, Escape)' },
      { type: 'new', text: 'Zvýraznění matchovaného textu v návrzích zastávek' },
      { type: 'new', text: 'Zobrazení počtu nalezených výsledků a loading stavu' },
      { type: 'improve', text: 'Zavření dropdownu kliknutím mimo oblast' },
      { type: 'improve', text: 'Podpora dlouhých názvů zastávek (např. Brandýs nad Labem-St. Boleslav)' },
      { type: 'improve', text: 'ARIA atributy pro přístupnost (combobox, listbox)' },
      { type: 'fix', text: 'Oprava race condition — abortnutý fetch přepisoval loading stav při rychlém psaní' },
      { type: 'new', text: 'Vyhledávání zastávek i uvnitř názvu — např. „Zahradní město" najde i Brandýs nad Labem-St. Boleslav, Zahradní Město' },
    ],
  },
  {
    version: '1.5.1',
    date: '5. 2. 2026',
    title: 'Rozlišení duplicitních oborů v simulátoru',
    changes: [
      { type: 'fix', text: 'Zobrazení zaměření/pobočky u oborů v simulátoru - odstraněny vizuální duplikáty' },
    ],
  },
  {
    version: '1.5.0',
    date: '5. 2. 2026',
    title: 'UX/UI audit a opravy přístupnosti',
    changes: [
      { type: 'fix', text: 'Přidán Header a Footer na stránku Jak funguje přijímání' },
      { type: 'fix', text: 'Responsivní SVG diagram (nahrazena fixní šířka 700px)' },
      { type: 'new', text: 'Mobilní card view pro Top 50 škol na /skoly' },
      { type: 'new', text: 'Mobilní card view pro Top 10 oborů na /regiony' },
      { type: 'improve', text: 'Numerická mobilní klávesnice pro zadávání bodů v simulátoru' },
      { type: 'improve', text: 'Responsivní legenda na stránce /skoly' },
      { type: 'improve', text: 'Breadcrumb navigace na stránce Jak funguje přijímání' },
      { type: 'improve', text: 'Footer grid layout pro tablety (sm:grid-cols-2)' },
      { type: 'new', text: 'UX/UI audit report (AUDIT.md)' },
    ],
  },
  {
    version: '1.4.0',
    date: '5. 2. 2026',
    title: 'Mobilní responsivita',
    changes: [
      { type: 'improve', text: 'Přidáno hamburger menu pro mobilní zařízení v hlavičce' },
      { type: 'improve', text: 'Responsivní layout tlačítek délky studia v simulátoru' },
      { type: 'improve', text: 'Přepracované karty škol pro mobilní zobrazení (dvouřádkový layout)' },
      { type: 'improve', text: 'Zkrácené texty prioritních tlačítek na mobilech' },
      { type: 'improve', text: 'Kompaktní legenda v přehledu regionů pro malé obrazovky' },
    ],
  },
  {
    version: '1.3.0',
    date: '4. 2. 2026',
    title: 'Nová struktura škol a průvodce',
    changes: [
      { type: 'new', text: 'Nová dvoustupňová struktura stránek škol: Přehled školy + Detail oboru/zaměření' },
      { type: 'new', text: 'Navigace mezi obory školy pomocí tabů' },
      { type: 'new', text: 'Stránka "Jak vybrat školu a uspět u přijímaček" - praktický průvodce' },
      { type: 'new', text: 'Aliasy pro PORG pobočky ve vyhledávání' },
      { type: 'new', text: 'Odkaz na průvodce v hlavičce a patičce' },
      { type: 'fix', text: 'Oprava duplicitních názvů oborů - přidání délky studia pro rozlišení' },
      { type: 'fix', text: 'Oprava duplicitních URL pro programy se stejným názvem' },
      { type: 'fix', text: 'Oprava navigace oborů - rozlišení KKOV vs. zaměření' },
      { type: 'improve', text: 'Varování o extra bodech za prospěch u škol s dodatečnými kritérii' },
    ],
  },
  {
    version: '1.2.0',
    date: '29. 1. 2026',
    title: 'Vyhledávání a opravy bodového systému',
    changes: [
      { type: 'new', text: 'Vyhledávání škol na titulní stránce a stránce /skoly' },
      { type: 'new', text: 'Analýza kohort přijatých studentů' },
      { type: 'fix', text: 'Oprava zobrazení bodů JPZ - převod z procentuálních skórů na skutečné body' },
      { type: 'fix', text: 'Oprava zobrazení minimálních bodů JPZ - skutečná data z raw dat uchazečů' },
      { type: 'fix', text: 'Oprava tabulky regionů - Body min a Body průměr místo Skóre' },
      { type: 'fix', text: 'Oprava simulátoru - použití čistých JPZ bodů místo celkového skóre' },
      { type: 'improve', text: 'Oprava komponenty TestDifficulty pro přesnější zobrazení' },
    ],
  },
  {
    version: '1.1.0',
    date: '25. 1. 2026',
    title: 'Simulátor a rozšířené funkce',
    changes: [
      { type: 'new', text: 'Rozšíření simulátoru se srovnávacími kartami škol a drag & drop řazením' },
      { type: 'new', text: 'Open Graph obrázky pro sdílení na sociálních sítích' },
      { type: 'new', text: 'Rozšířené funkce detailu školy a přehledu regionů' },
      { type: 'fix', text: 'Oprava zobrazení souvisejících škol' },
    ],
  },
  {
    version: '1.0.0',
    date: '24. 1. 2026',
    title: 'První verze',
    changes: [
      { type: 'new', text: 'Simulátor přijímacích zkoušek s reálnými daty z CERMAT' },
      { type: 'new', text: 'Přehled škol podle regionů a krajů' },
      { type: 'new', text: 'Detail školy s bodovými statistikami a indexem poptávky' },
      { type: 'new', text: 'SEO optimalizace s dynamickými URL' },
      { type: 'new', text: 'Migrace na Next.js s App Router' },
    ],
  },
];

export const AKTUALNI_VERZE = changelog[0].version;
