// Sdílený seznam měst pro stránky i sitemapu.
//
// NEUPRAVOVAT RUČNĚ. Generuje `scripts/build-mesta.py` z katalogu
// za ročník 2026 podle registru stavu datových sad. Do seznamu jde
// obec s aspoň 3 školami a všechna města zveřejněná dřív,
// aby se nerozbily odkazy. Řazeno podle počtu škol.
export const MESTA = /** @type {const} */ ([
  { nazev: 'Praha', slug: 'praha', kraj: 'Hlavní město Praha' },
  { nazev: 'Brno', slug: 'brno', kraj: 'Jihomoravský kraj' },
  { nazev: 'Ostrava', slug: 'ostrava', kraj: 'Moravskoslezský kraj' },
  { nazev: 'Plzeň', slug: 'plzen', kraj: 'Plzeňský kraj' },
  { nazev: 'České Budějovice', slug: 'ceske-budejovice', kraj: 'Jihočeský kraj' },
  { nazev: 'Olomouc', slug: 'olomouc', kraj: 'Olomoucký kraj' },
  { nazev: 'Hradec Králové', slug: 'hradec-kralove', kraj: 'Královéhradecký kraj' },
  { nazev: 'Liberec', slug: 'liberec', kraj: 'Liberecký kraj' },
  { nazev: 'Pardubice', slug: 'pardubice', kraj: 'Pardubický kraj' },
  { nazev: 'Mladá Boleslav', slug: 'mlada-boleslav', kraj: 'Středočeský kraj' },
  { nazev: 'Opava', slug: 'opava', kraj: 'Moravskoslezský kraj' },
  { nazev: 'Prostějov', slug: 'prostejov', kraj: 'Olomoucký kraj' },
  { nazev: 'Frýdek-Místek', slug: 'frydek-mistek', kraj: 'Moravskoslezský kraj' },
  { nazev: 'Jihlava', slug: 'jihlava', kraj: 'Kraj Vysočina' },
  { nazev: 'Kladno', slug: 'kladno', kraj: 'Středočeský kraj' },
  { nazev: 'Zlín', slug: 'zlin', kraj: 'Zlínský kraj' },
  { nazev: 'Karlovy Vary', slug: 'karlovy-vary', kraj: 'Karlovarský kraj' },
  { nazev: 'Kroměříž', slug: 'kromeriz', kraj: 'Zlínský kraj' },
  { nazev: 'Most', slug: 'most', kraj: 'Ústecký kraj' },
  { nazev: 'Ústí nad Labem', slug: 'usti-nad-labem', kraj: 'Ústecký kraj' },
  { nazev: 'Havířov', slug: 'havirov', kraj: 'Moravskoslezský kraj' },
  { nazev: 'Kolín', slug: 'kolin', kraj: 'Středočeský kraj' },
  { nazev: 'Tábor', slug: 'tabor', kraj: 'Jihočeský kraj' },
  { nazev: 'Beroun', slug: 'beroun', kraj: 'Středočeský kraj' },
  { nazev: 'Chrudim', slug: 'chrudim', kraj: 'Pardubický kraj' },
  { nazev: 'Děčín', slug: 'decin', kraj: 'Ústecký kraj' },
  { nazev: 'Písek', slug: 'pisek', kraj: 'Jihočeský kraj' },
  { nazev: 'Přerov', slug: 'prerov', kraj: 'Olomoucký kraj' },
  { nazev: 'Třebíč', slug: 'trebic', kraj: 'Kraj Vysočina' },
  { nazev: 'Česká Lípa', slug: 'ceska-lipa', kraj: 'Liberecký kraj' },
  { nazev: 'Karviná', slug: 'karvina', kraj: 'Moravskoslezský kraj' },
  { nazev: 'Litoměřice', slug: 'litomerice', kraj: 'Ústecký kraj' },
  { nazev: 'Poděbrady', slug: 'podebrady', kraj: 'Středočeský kraj' },
  { nazev: 'Příbram', slug: 'pribram', kraj: 'Středočeský kraj' },
  { nazev: 'Šumperk', slug: 'sumperk', kraj: 'Olomoucký kraj' },
  { nazev: 'Uherské Hradiště', slug: 'uherske-hradiste', kraj: 'Zlínský kraj' },
  { nazev: 'Žďár nad Sázavou', slug: 'zdar-nad-sazavou', kraj: 'Kraj Vysočina' },
  { nazev: 'Znojmo', slug: 'znojmo', kraj: 'Jihomoravský kraj' },
  { nazev: 'Hranice', slug: 'hranice', kraj: 'Olomoucký kraj' },
  { nazev: 'Jablonec nad Nisou', slug: 'jablonec-nad-nisou', kraj: 'Liberecký kraj' },
  { nazev: 'Kutná Hora', slug: 'kutna-hora', kraj: 'Středočeský kraj' },
  { nazev: 'Mělník', slug: 'melnik', kraj: 'Středočeský kraj' },
  { nazev: 'Sokolov', slug: 'sokolov', kraj: 'Karlovarský kraj' },
  { nazev: 'Teplice', slug: 'teplice', kraj: 'Ústecký kraj' },
  { nazev: 'Trutnov', slug: 'trutnov', kraj: 'Královéhradecký kraj' },
  { nazev: 'Valašské Meziříčí', slug: 'valasske-mezirici', kraj: 'Zlínský kraj' },
  { nazev: 'Žatec', slug: 'zatec', kraj: 'Ústecký kraj' },
  { nazev: 'Benešov', slug: 'benesov', kraj: 'Středočeský kraj' },
  { nazev: 'Blansko', slug: 'blansko', kraj: 'Jihomoravský kraj' },
  { nazev: 'Boskovice', slug: 'boskovice', kraj: 'Jihomoravský kraj' },
  { nazev: 'Čáslav', slug: 'caslav', kraj: 'Středočeský kraj' },
  { nazev: 'Český Těšín', slug: 'cesky-tesin', kraj: 'Moravskoslezský kraj' },
  { nazev: 'Cheb', slug: 'cheb', kraj: 'Karlovarský kraj' },
  { nazev: 'Chomutov', slug: 'chomutov', kraj: 'Ústecký kraj' },
  { nazev: 'Havlíčkův Brod', slug: 'havlickuv-brod', kraj: 'Kraj Vysočina' },
  { nazev: 'Jeseník', slug: 'jesenik', kraj: 'Olomoucký kraj' },
  { nazev: 'Jičín', slug: 'jicin', kraj: 'Královéhradecký kraj' },
  { nazev: 'Jindřichův Hradec', slug: 'jindrichuv-hradec', kraj: 'Jihočeský kraj' },
  { nazev: 'Klatovy', slug: 'klatovy', kraj: 'Plzeňský kraj' },
  { nazev: 'Krnov', slug: 'krnov', kraj: 'Moravskoslezský kraj' },
  { nazev: 'Litomyšl', slug: 'litomysl', kraj: 'Pardubický kraj' },
  { nazev: 'Litvínov', slug: 'litvinov', kraj: 'Ústecký kraj' },
  { nazev: 'Náchod', slug: 'nachod', kraj: 'Královéhradecký kraj' },
  { nazev: 'Nová Paka', slug: 'nova-paka', kraj: 'Královéhradecký kraj' },
  { nazev: 'Nový Jičín', slug: 'novy-jicin', kraj: 'Moravskoslezský kraj' },
  { nazev: 'Pelhřimov', slug: 'pelhrimov', kraj: 'Kraj Vysočina' },
  { nazev: 'Rakovník', slug: 'rakovnik', kraj: 'Středočeský kraj' },
  { nazev: 'Roudnice nad Labem', slug: 'roudnice-nad-labem', kraj: 'Ústecký kraj' },
  { nazev: 'Rožnov pod Radhoštěm', slug: 'roznov-pod-radhostem', kraj: 'Zlínský kraj' },
  { nazev: 'Uherský Brod', slug: 'uhersky-brod', kraj: 'Zlínský kraj' },
  { nazev: 'Ústí nad Orlicí', slug: 'usti-nad-orlici', kraj: 'Pardubický kraj' },
  { nazev: 'Vlašim', slug: 'vlasim', kraj: 'Středočeský kraj' },
  { nazev: 'Vsetín', slug: 'vsetin', kraj: 'Zlínský kraj' },
  { nazev: 'Vysoké Mýto', slug: 'vysoke-myto', kraj: 'Pardubický kraj' },
  { nazev: 'Břeclav', slug: 'breclav', kraj: 'Jihomoravský kraj' },
  { nazev: 'Dobruška', slug: 'dobruska', kraj: 'Královéhradecký kraj' },
  { nazev: 'Domažlice', slug: 'domazlice', kraj: 'Plzeňský kraj' },
  { nazev: 'Hodonín', slug: 'hodonin', kraj: 'Jihomoravský kraj' },
  { nazev: 'Hořice', slug: 'horice', kraj: 'Královéhradecký kraj' },
  { nazev: 'Humpolec', slug: 'humpolec', kraj: 'Kraj Vysočina' },
  { nazev: 'Lanškroun', slug: 'lanskroun', kraj: 'Pardubický kraj' },
  { nazev: 'Lipník nad Bečvou', slug: 'lipnik-nad-becvou', kraj: 'Olomoucký kraj' },
  { nazev: 'Mariánské Lázně', slug: 'marianske-lazne', kraj: 'Karlovarský kraj' },
  { nazev: 'Moravská Třebová', slug: 'moravska-trebova', kraj: 'Pardubický kraj' },
  { nazev: 'Nymburk', slug: 'nymburk', kraj: 'Středočeský kraj' },
  { nazev: 'Orlová', slug: 'orlova', kraj: 'Moravskoslezský kraj' },
  { nazev: 'Polička', slug: 'policka', kraj: 'Pardubický kraj' },
  { nazev: 'Říčany', slug: 'ricany', kraj: 'Středočeský kraj' },
  { nazev: 'Rumburk', slug: 'rumburk', kraj: 'Ústecký kraj' },
  { nazev: 'Semily', slug: 'semily', kraj: 'Liberecký kraj' },
  { nazev: 'Slaný', slug: 'slany', kraj: 'Středočeský kraj' },
  { nazev: 'Strakonice', slug: 'strakonice', kraj: 'Jihočeský kraj' },
  { nazev: 'Strážnice', slug: 'straznice', kraj: 'Jihomoravský kraj' },
  { nazev: 'Svitavy', slug: 'svitavy', kraj: 'Pardubický kraj' },
  { nazev: 'Tišnov', slug: 'tisnov', kraj: 'Jihomoravský kraj' },
  { nazev: 'Třeboň', slug: 'trebon', kraj: 'Jihočeský kraj' },
  { nazev: 'Třinec', slug: 'trinec', kraj: 'Moravskoslezský kraj' },
  { nazev: 'Turnov', slug: 'turnov', kraj: 'Liberecký kraj' },
  { nazev: 'Uničov', slug: 'unicov', kraj: 'Olomoucký kraj' },
  { nazev: 'Varnsdorf', slug: 'varnsdorf', kraj: 'Ústecký kraj' },
  { nazev: 'Vodňany', slug: 'vodnany', kraj: 'Jihočeský kraj' },
  { nazev: 'Zábřeh', slug: 'zabreh', kraj: 'Olomoucký kraj' },
]);
