import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  sestavSkupiny, zprava, polozkaPr, uvodIssue, terminPripominky, potrebujeSouhlas, html, MAX_V_SKUPINE, MAX_TLACITEK, UVIZLA_PO, jedenOdstavec,
} from '../scripts/prehled/ceka-na-tebe.mjs';

const TED = Date.parse('2026-10-08T07:00:00Z');
const DNES = '2026-10-08';
const ucty = { vlastnik: 'tangero', asistent: 'eduarda-prijimacky' };
const PATICKA = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
const TELO_PR = 'Closes #10\n\n## Pro vlastníka\nMísto krátkého jména Gymnazium uvidíš celý oficiální název školy.\nAdresa: /skola/600001234-gymnazium\n\n## Jak ověřit\nnic';
const pr = (o = {}) => ({ cislo: 5, titulek: 'Celé názvy škol', telo: TELO_PR, stitky: [], souhlas: true, nahled: 'https://stredniskoly-abc.vercel.app', ...o });
const issue = (o = {}) => ({ cislo: 20, titulek: 'Návrh', telo: 'Zdroj: vlastník\n\n## Problém\nRodiče nevidí body na první pohled.', stitky: ['interni', 'navrh'], komentare: [], upraveno: '2026-10-07T00:00:00Z', ...o });
const skupiny = (o) => sestavSkupiny({ prs: [], issues: [], ucty, dnes: DNES, ted: TED, ...o });

test('PR ke schválení: lidská věta z oddílu Pro vlastníka a odkaz na stránku v náhledu', () => {
  const p = polozkaPr(pr(), { nahled: 'https://stredniskoly-abc.vercel.app' });
  assert.match(p.radky[0], /^Na stránce <a href="https:\/\/stredniskoly-abc\.vercel\.app\/skola\/600001234-gymnazium">\/skola\/600001234-gymnazium<\/a> zkontroluj: Místo krátkého jména Gymnazium/);
  assert.doesNotMatch(p.radky[0], /Adresa:/);
  // Bez náhledu jen cesta jako text a vysvětlení.
  const bez = polozkaPr(pr(), { nahled: null });
  assert.match(bez.radky[0], /<code>\/skola\/600001234-gymnazium<\/code>/);
  assert.match(bez.radky[1], /Náhled zatím není/);
});

test('skupiny v pořadí pro vlastníka, prázdné se vynechají', () => {
  const g = skupiny({
    prs: [pr(), pr({ cislo: 6, souhlas: false, stitky: ['potrebuje-cloveka'] }), pr({ cislo: 7, souhlas: false })],
    issues: [
      issue(),
      issue({ cislo: 21, stitky: ['interni', 'otazka'], komentare: [{ autor: 'tangero', telo: `Mám použít data za rok 2026, nebo 2025?${PATICKA}` }] }),
      issue({ cislo: 22, komentare: [{ autor: 'github-actions[bot]', telo: '## Oponentura\n\nVarianty A a B.' }] }),
      issue({ cislo: 23, stitky: ['interni', 'pripominka'], telo: 'Termín: 2026-10-08\n\nVyhodnotit sklizeň.' }),
      issue({ cislo: 24, stitky: ['interni', 'pripominka'], telo: 'Termín: 2026-11-01\n\nPozději.' }),
      issue({ cislo: 25, stitky: ['interni', 'navrh', 'zamitnuto'] }),
    ],
  });
  assert.deepEqual(g.map((x) => x.klic), ['souhlas', 'otazka', 'oponentura', 'navrh', 'pripominka', 'clovek']);
  assert.deepEqual(g.map((x) => x.polozky.map((p) => p.cislo)), [[5], [21], [22], [20], [23], [6]]);
  assert.match(g[1].polozky[0].radky[0], /Mám použít data za rok 2026/);
  assert.doesNotMatch(g[1].polozky[0].radky[0], /Generated by/);
  assert.equal(g[3].polozky[0].radky[0], 'Rodiče nevidí body na první pohled.');
});

test('oponentura uvízne až po třech hodinách se štítkem', () => {
  const op = (h) => issue({ stitky: ['interni', 'oponentura'], oponenturaOd: new Date(TED - h * 3600 * 1000).toISOString() });
  assert.equal(skupiny({ issues: [op(1)] }).length, 0);
  assert.equal(skupiny({ issues: [op(UVIZLA_PO / 3600000)] })[0].klic, 'uvizla');
});

test('zpráva: HTML Telegramu, tlačítka dvě na řádek, strop položek a tlačítek', () => {
  const g = skupiny({ prs: Array.from({ length: 20 }, (_, i) => pr({ cislo: 100 + i, titulek: `Změna <${i}> & spol.` })) });
  const z = zprava(g);
  assert.match(z.text, /^<b>Čeká na tebe: 20<\/b>/);
  assert.match(z.text, /Změna &lt;0&gt; &amp; spol\./);
  assert.match(z.text, new RegExp(`…a dalších ${20 - MAX_V_SKUPINE}`));
  assert.match(z.text, /štítek <code>schvaleno<\/code>/);
  const vsechna = z.tlacitka.flat();
  assert.equal(vsechna.length, MAX_V_SKUPINE);
  assert.ok(vsechna.length <= MAX_TLACITEK);
  assert.ok(z.tlacitka.every((r) => r.length <= 2));
  assert.deepEqual(vsechna[0], { text: '#100 schválit', url: 'https://github.com/tangero/stredniskoly/pull/100' });
  assert.ok(z.text.length < 4096);
});

test('pomocné funkce', () => {
  assert.equal(html('a < b & "c"'), 'a &lt; b &amp; &quot;c&quot;');
  assert.equal(terminPripominky('Termín: 2026-10-08'), '2026-10-08');
  assert.equal(terminPripominky('bez'), null);
  assert.equal(uvodIssue('Zdroj: vlastník\n\n## Rozsah\n- [ ] K1: x\n\nText **tučně** a [odkaz](https://x).'), 'Text tučně a odkaz.');
  assert.equal(potrebujeSouhlas({ conclusion: 'failure', output: { summary: '- mění pravomoci AI (x): chybí souhlas vlastníka (bez štítku)' } }), true);
  assert.equal(potrebujeSouhlas({ conclusion: 'failure', output: { summary: '- chybí review asistenta zadání' } }), false);
  assert.equal(potrebujeSouhlas({ conclusion: 'success', output: { summary: 'chybí souhlas vlastníka' } }), false);
  assert.equal(potrebujeSouhlas(undefined), false);
});

test('hlášení od veřejnosti jako skupina, včetně hlášení škol, trvalá issue ne (#461)', () => {
  const g = skupiny({ issues: [
    issue({ cislo: 30, stitky: ['bug-report', 'oblast:detail'] }),
    issue({ cislo: 31, stitky: ['bug-report', 'schvaleno'] }),
    issue({ cislo: 32, stitky: ['portal-skoly', 'oblast:portal'] }),
    issue({ cislo: 33, stitky: ['interni', 'trvale', 'rutina', 'navrh'] }),
  ] });
  assert.deepEqual(g.map((x) => [x.klic, x.polozky.map((p) => p.cislo)]), [['hlaseni', [30]]]);
});

test('otázka jako jeden odstavec bez nadpisů a tabulek (#461)', () => {
  assert.equal(jedenOdstavec('## Otázka pro vlastníka\n\n| a | b |\n|---|---|\n- Platí to **i** pro [rok](https://x)?'), 'Otázka pro vlastníka Platí to i pro rok?');
});
