import { test } from 'node:test';
import assert from 'node:assert/strict';
import { jeOdpoved, textOtazky, zprava } from '../scripts/brana/otazka.mjs';

const ucty = { vlastnik: 'tangero', asistent: 'eduarda-prijimacky' };
const AI = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';

test('odpověď: komentář vlastníka bez patičky AI, nebo zápis s nadpisem Odpověď vlastníka', () => {
  assert.equal(jeOdpoved({ autor: 'tangero', telo: 'u všech škol' }, ucty), true);
  assert.equal(jeOdpoved({ autor: 'tangero', telo: `Před začátkem práce se ptám…${AI}` }, ucty), false);
  assert.equal(jeOdpoved({ autor: 'tangero', telo: `## Odpověď vlastníka\n\n1. u všech${AI}` }, ucty), true);
  assert.equal(jeOdpoved({ autor: 'eduarda-prijimacky', telo: '## Odpověď vlastníka\n\nano' }, ucty), true);
  assert.equal(jeOdpoved({ autor: 'eduarda-prijimacky', telo: '## Review\n\nVerdikt: Bez P1 a P2' }, ucty), false);
  assert.equal(jeOdpoved({ autor: 'nekdo', telo: '## Odpověď vlastníka\n\nano' }, ucty), false);
});

test('text otázky: poslední komentář AI, který není odpovědí, bez patičky a zkrácený', () => {
  const komentare = [
    { autor: 'tangero', telo: `Starší otázka${AI}` },
    { autor: 'github-actions[bot]', telo: 'Brána zaznamenala souhlas' },
    { autor: 'tangero', telo: `Před začátkem práce se ptám:\n\n1. **Celoplošně**, nebo jen u školy?${AI}` },
    { autor: 'nekdo', telo: `Podvržená otázka${AI}` },
  ];
  assert.equal(textOtazky(komentare, ucty), 'Před začátkem práce se ptám:\n\n1. Celoplošně, nebo jen u školy?');
  assert.equal(textOtazky([{ autor: 'tangero', telo: 'bez patičky' }], ucty), '');
  assert.equal(textOtazky([{ autor: 'tangero', telo: `${'x'.repeat(2000)}${AI}` }], ucty).length, 1500);
});

test('zpráva nese číslo, název, otázku a odkaz', () => {
  const t = zprava({ cislo: 370, titulek: 'SZŠ Beroun', url: 'https://github.com/tangero/stredniskoly/issues/370', text: 'Celoplošně?' });
  assert.match(t, /^Otázka k #370 SZŠ Beroun\n\nCeloplošně\?\n\nOdpověz komentářem v issue, nebo řekni Eduardě či Claude Code:\nhttps:\/\/github\.com\/tangero\/stredniskoly\/issues\/370$/);
});

test('text otázky: komentář, který se ptá, ne pozdější ohlášení stahování (#461)', () => {
  const P = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
  const ucty = { vlastnik: 'tangero', asistent: 'eduarda-prijimacky' };
  const komentare = [
    { autor: 'tangero', telo: `## Otázka pro vlastníka\n\nMá oprava platit i pro starší ročníky?${P}` },
    { autor: 'tangero', telo: `## Ohlášení stahování (pravidlo 7)\n\nStáhnu jednou čtyři stránky.${P}` },
  ];
  assert.match(textOtazky(komentare, ucty), /starší ročníky\?/);
  // Když se žádný komentář neptá, pošle se poslední komentář AI jako dřív.
  assert.match(textOtazky(komentare.slice(1), ucty), /Ohlášení stahování/);
});
