// Měřítka vývoje pro týdenní přehled (docs/navrh-rizeni-vyvoje-2027.md, oddíl 20; zadání #324).
//
// Počítá se jen z GitHubu tohoto repozitáře, bez vlastního úložiště: sloučené PR s propojeným zadáním
// (Closes / Souvisí s #N), události štítků a komentáře. Načítání (nactiMeritka) je oddělené od výpočtu
// (spocitejMeritka), aby šel výpočet testovat na fixture bez sítě.

import { REPO, NAZEV_KONTROLY } from '../brana/data.mjs';
import { propojenaIssues } from '../brana/brana.mjs';

const DEN = 24 * 60 * 60 * 1000;
export const OKNO = 28 * DEN;
export const LHUTA_OPRAVY = 14 * DEN;
// Komentáře, které nepsal člověk: patička Claude Code nebo strojová značka (brána, smyčka oprav, sloučení).
const STROJOVY = /Generated by \[Claude Code\]|<!-- [a-z-]+[:=]/;
// Přes účet vlastníka píší i Claude Code a review jiných modelů. Lidský komentář je krátký, nezačíná
// nadpisem a nemá řádek Commit: (odhad; zásahy se proto zapisují výslovně řádkem Zásah:).
export const psalClovek = (telo = '') => !STROJOVY.test(telo) && telo.length < 400 && !/^\s*#/.test(telo) && !/^Commit:/m.test(telo);
const ZNACKA_KOLA = /<!-- oprava-z-review:kolo=(\d+) -->/;
const ZASAH = /^\s*Zásah:\s*(\d+)\s*min\b\s*[-–:]?\s*(.*)$/im;
// Bez \b: za „í“ by hranice slova bez příznaku u nenastala.
const VRACENI = /^\s*(?:#+\s*)?(Změna zadání|Dotaz)(?=[\s:.,]|$)/i;

export const FAZE = {
  naSchvaleni: 'na schválení vlastníkem',
  naRealizaci: 'na realizaci (AI)',
  vPr: 'v PR (brána, review, lhůta)',
};

const cas = (iso) => (iso ? Date.parse(iso) : null);

export function median(cisla) {
  const s = cisla.filter((c) => Number.isFinite(c)).sort((a, b) => a - b);
  if (!s.length) return null;
  const m = Math.floor(s.length / 2);
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
}

/** Režim z titulku kontroly brány („Prošlo (R)“); starší PR bez brány mají „neznámý“. */
export function rezimZBrany(titulek) {
  const m = (titulek || '').match(/\((R|L|E|K|H2|souhlas)\)/);
  return m ? m[1] : 'neznámý';
}

/** Ruční zásah z komentáře: vlastník, nebo asistent zadání s odkazem na zápis z briefingu. */
export function zasah(komentar, { vlastnik, asistent }) {
  const m = (komentar.telo || '').match(ZASAH);
  if (!m) return null;
  const odVlastnika = komentar.autor === vlastnik;
  const odAsistenta = asistent && komentar.autor === asistent && /https?:\/\//.test(komentar.telo);
  if (!odVlastnika && !odAsistenta) return null;
  return { minuty: Number(m[1]), duvod: m[2].trim(), cislo: komentar.cislo, kdo: komentar.autor, kdy: komentar.kdy };
}

/** Je `q` revert nebo oprava PR `p` do 14 dnů od jeho sloučení? */
function opravuje(q, p, issue) {
  if (!q.slouceno || q.cislo === p.cislo) return false;
  const dt = cas(q.slouceno) - cas(p.slouceno);
  if (dt <= 0 || dt > LHUTA_OPRAVY) return false;
  const text = `${q.titulek}\n${q.telo || ''}`;
  if (/^Revert\b/i.test(q.titulek) && (text.includes(`#${p.cislo}`) || text.includes(p.titulek))) return true;
  // Další PR k témuž zadání; u projektů jsou další PR etapy, ne opravy.
  return Boolean(issue) && !issue.stitky.includes('projekt') && propojenaIssues(q.telo).includes(issue.cislo);
}

/**
 * Výpočet měřítek. Vstup:
 *   pulls: zavřené PR { cislo, titulek, telo, vytvoreno, slouceno|null, stitky[] }
 *   issues: { [cislo]: { cislo, vytvoreno, stitky[], schvaleno|null, cekaNaOdpoved[] } }
 *   rezimy: { [cislo PR]: titulek kontroly brány }
 *   komentare: { cislo, autor, telo, kdy } (issues i PR)
 *   akce: { rozhodnuti } počet přidaných štítků schvaleno, zamitnuto a stop z účtu vlastníka za týden
 *   navrhy: otevřené návrhy { cislo, od }
 */
export function spocitejMeritka({ pulls, issues, rezimy, komentare, akce, navrhy }, { ted, vlastnik, asistent }) {
  const komentarePodle = new Map();
  for (const k of komentare) {
    if (!komentarePodle.has(k.cislo)) komentarePodle.set(k.cislo, []);
    komentarePodle.get(k.cislo).push(k);
  }

  const zadani = [];
  for (const p of pulls.filter((x) => x.slouceno && ted - cas(x.slouceno) <= 2 * OKNO)) {
    const cislaIssues = propojenaIssues(p.telo).filter((n) => issues[n]);
    if (!cislaIssues.length) continue;
    const issue = issues[cislaIssues[0]];
    // Všechny PR k zadání (i zavřené bez sloučení); první z nich určuje začátek realizace.
    const prKZadani = pulls.filter((q) => propojenaIssues(q.telo).includes(issue.cislo));
    const tPr = Math.min(...prKZadani.map((q) => cas(q.vytvoreno)));
    const t0 = Math.min(cas(issue.vytvoreno), tPr);
    const tSchv = cas(issue.schvaleno);
    const tMerge = cas(p.slouceno);
    const start = tSchv && tSchv < tPr ? tSchv : t0;
    const faze = {
      // Schválení až po začátku realizace (#342) do fáze „na schválení“ nepatří, jinak by se překrývala s realizací.
      naSchvaleni: tSchv && tSchv > t0 && tSchv <= tPr ? tSchv - t0 : null,
      naRealizaci: Math.max(0, tPr - start),
      vPr: tMerge - tPr,
    };
    const kola = (komentarePodle.get(p.cislo) || [])
      .map((k) => Number((k.telo.match(ZNACKA_KOLA) || [])[1] || 0))
      .reduce((a, b) => Math.max(a, b), 0);
    const vraceniKomentarem = (komentarePodle.get(issue.cislo) || [])
      .some((k) => cas(k.kdy) > tPr && VRACENI.test(k.telo));
    const zavrenyBezSlouceni = prKZadani.some((q) => !q.slouceno && q.cislo !== p.cislo);
    const cekaloNaOdpoved = (issue.cekaNaOdpoved || []).some((kdy) => cas(kdy) > tPr);
    zadani.push({
      pr: p.cislo, issue: issue.cislo, titulek: p.titulek,
      rezim: rezimZBrany(rezimy[p.cislo]),
      slouceno: p.slouceno,
      celkem: tMerge - t0,
      faze,
      kola,
      potrebujeCloveka: p.stitky.includes('potrebuje-cloveka'),
      oprava: pulls.find((q) => opravuje(q, p, issue))?.cislo ?? null,
      lhutaUplynula: ted - tMerge >= LHUTA_OPRAVY,
      vraceno: vraceniKomentarem || zavrenyBezSlouceni || cekaloNaOdpoved,
    });
  }

  const posledni = zadani.filter((z) => ted - cas(z.slouceno) <= OKNO);
  const predchozi = zadani.filter((z) => ted - cas(z.slouceno) > OKNO);
  const medianyPodleRezimu = (pole) => {
    const podle = {};
    for (const z of pole) (podle[z.rezim] ||= []).push(z.celkem);
    return Object.fromEntries(Object.entries(podle).map(([r, d]) => [r, { median: median(d), pocet: d.length }]));
  };

  const cekani = posledni.flatMap((z) => Object.entries(z.faze)
    .filter(([, d]) => d !== null)
    .map(([faze, d]) => ({ pr: z.pr, issue: z.issue, titulek: z.titulek, faze, trvani: d })))
    .sort((a, b) => b.trvani - a.trvani)
    .slice(0, 5);

  const tyden = komentare.filter((k) => ted - cas(k.kdy) <= 7 * DEN);
  const zasahy = tyden.map((k) => zasah(k, { vlastnik, asistent })).filter(Boolean);
  const komentareVlastnika = tyden.filter((k) => k.autor === vlastnik && psalClovek(k.telo)).length;

  const nejstarsiNavrh = navrhy.length ? Math.max(...navrhy.map((n) => ted - cas(n.od))) : null;

  return {
    zadani: posledni,
    median: median(posledni.map((z) => z.celkem)),
    medianPredchozi: median(predchozi.map((z) => z.celkem)),
    podleRezimu: medianyPodleRezimu(posledni),
    podleRezimuPredchozi: medianyPodleRezimu(predchozi),
    opravy: { pocet: posledni.filter((z) => z.oprava).length, z: posledni.length, predchozi: predchozi.filter((z) => z.oprava).length, zPredchozich: predchozi.length },
    vraceno: { pocet: posledni.filter((z) => z.vraceno).length, z: posledni.length },
    cekani,
    zasahy,
    minutyZasahu: zasahy.reduce((s, z) => s + z.minuty, 0),
    akceVlastnika: { ...akce, komentare: komentareVlastnika },
    nejstarsiNavrh,
  };
}

const dny = (ms) => (ms === null || ms === undefined ? '–' : `${(ms / DEN).toFixed(1)} d`);
const procenta = (a, b) => (b ? `${Math.round((100 * a) / b)} %` : '–');

/** Tři hlavní čísla do Telegramu. */
export function kratkaMeritka(m) {
  return `Měřítka (4 týdny): zadání→sloučení medián ${dny(m.median)}, opravy a reverty do 14 dnů ${procenta(m.opravy.pocet, m.opravy.z)}, ruční zásahy ${m.minutyZasahu} min za týden`;
}

/** Oddíl Měřítka do dlouhé verze přehledu (markdown). */
export function oddilMeritka(m, odkaz) {
  const rezimy = [...new Set([...Object.keys(m.podleRezimu), ...Object.keys(m.podleRezimuPredchozi)])].sort();
  return [
    '## Měřítka (oddíl 20 návrhu řízení)',
    'Zadání = sloučené PR s propojeným issue (`Closes` / `Souvisí s #N`). Okno 4 týdny, srovnání s předchozími 4 týdny.',
    '',
    `- Medián od založení zadání po sloučení: ${dny(m.median)} (předchozí 4 týdny ${dny(m.medianPredchozi)}), zadání: ${m.zadani.length}`,
    ...rezimy.map((r) => `  - režim ${r}: ${dny(m.podleRezimu[r]?.median)} (${m.podleRezimu[r]?.pocet || 0}×), předtím ${dny(m.podleRezimuPredchozi[r]?.median)} (${m.podleRezimuPredchozi[r]?.pocet || 0}×)`),
    `- Opravy a reverty do 14 dnů: ${m.opravy.pocet} z ${m.opravy.z} (${procenta(m.opravy.pocet, m.opravy.z)}), předtím ${m.opravy.predchozi} z ${m.opravy.zPredchozich}. U zadání sloučených v posledních 14 dnech lhůta ještě běží.`,
    `- Vráceno po naprogramování (změna zadání, dotaz, čeká na odpověď, PR zavřený bez sloučení): ${m.vraceno.pocet} z ${m.vraceno.z} (${procenta(m.vraceno.pocet, m.vraceno.z)})`,
    `- Akce z účtu vlastníka za týden: přidané štítky \`schvaleno\`, \`zamitnuto\`, \`stop\` ${m.akceVlastnika.rozhodnuti}, krátké komentáře psané nejspíš člověkem ${m.akceVlastnika.komentare}. Sloučení se nepočítají: workflow Sloučení slučuje tokenem vlastníka a ruční sloučení od něj nejde odlišit. Přes týž účet píší i Claude Code a review jiných modelů, počet komentářů je proto odhad.`,
    `- Ruční zásahy za týden: ${m.minutyZasahu} min (${m.zasahy.length}×). Počítají se jen zapsané komentáře \`Zásah: N min - důvod\`.`,
    ...m.zasahy.map((z) => `  - ${odkaz(z.cislo)} ${z.minuty} min: ${z.duvod || 'bez důvodu'}`),
    `- Nejstarší otevřený návrh: ${dny(m.nejstarsiNavrh)}`,
    '',
    '### Nejdelší čekání ve fázi',
    ...(m.cekani.length ? m.cekani.map((c) => `- ${dny(c.trvani)} ${FAZE[c.faze]}: ${odkaz(c.issue)} ${c.titulek} (PR ${odkaz(c.pr, true)})`) : ['- žádná zadání']),
    '',
    '### Sloučená zadání',
    '| PR | zadání | režim | na schválení | na realizaci | v PR | kola oprav | oprava do 14 dnů |',
    '|---|---|---|---|---|---|---|---|',
    ...m.zadani.map((z) => `| ${odkaz(z.pr, true)} | ${odkaz(z.issue)} | ${z.rezim} | ${dny(z.faze.naSchvaleni)} | ${dny(z.faze.naRealizaci)} | ${dny(z.faze.vPr)} | ${z.kola}${z.potrebujeCloveka ? ' (člověk)' : ''} | ${z.oprava ? odkaz(z.oprava, true) : z.lhutaUplynula ? 'ne' : 'lhůta běží'} |`),
  ].join('\n');
}

async function strankuj(api, cesta, staci) {
  const vse = [];
  for (let strana = 1; strana <= 30; strana++) {
    const dil = await api(`${cesta}${cesta.includes('?') ? '&' : '?'}per_page=100&page=${strana}`);
    vse.push(...dil);
    if (dil.length < 100 || staci(dil)) break;
  }
  return vse;
}

/** Načte vstup pro spocitejMeritka z GitHub API. `udalostiTydne` a `rozhodnuti` už načetl tydenni.mjs. */
export async function nactiMeritka(api, ted, { navrhy, udalostiTydne, vlastnik }) {
  const od = ted - 2 * OKNO;
  // Navíc 4 týdny zpět kvůli PR zavřeným bez sloučení a prvnímu PR k zadání.
  const zavrene = await strankuj(api, `repos/${REPO}/pulls?state=closed&sort=updated&direction=desc`,
    (dil) => Date.parse(dil[dil.length - 1].updated_at) < od - OKNO);
  const pulls = zavrene
    .filter((p) => Date.parse(p.closed_at) >= od - OKNO)
    .map((p) => ({ cislo: p.number, titulek: p.title, telo: p.body || '', vytvoreno: p.created_at, slouceno: p.merged_at, stitky: p.labels.map((l) => l.name), sha: p.head.sha }));

  const sloucene = pulls.filter((p) => p.slouceno && Date.parse(p.slouceno) >= od);
  const cislaIssues = [...new Set(sloucene.flatMap((p) => propojenaIssues(p.telo)))];
  const issues = {};
  for (const n of cislaIssues) {
    const i = await api(`repos/${REPO}/issues/${n}`).catch(() => null);
    if (!i || i.pull_request) continue;
    const udalosti = await strankuj(api, `repos/${REPO}/issues/${n}/events`, () => false);
    const prvni = (stitek) => udalosti.filter((u) => u.event === 'labeled' && u.label?.name === stitek).map((u) => u.created_at);
    issues[n] = {
      cislo: n, vytvoreno: i.created_at, stitky: i.labels.map((l) => l.name),
      schvaleno: prvni('schvaleno').sort()[0] || null,
      cekaNaOdpoved: prvni('ceka-na-odpoved'),
    };
  }

  const rezimy = {};
  for (const p of sloucene.filter((x) => propojenaIssues(x.telo).some((n) => issues[n]))) {
    const d = await api(`repos/${REPO}/commits/${p.sha}/check-runs?check_name=${encodeURIComponent(NAZEV_KONTROLY)}&filter=latest`);
    rezimy[p.cislo] = (d.check_runs || []).sort((a, b) => b.id - a.id)[0]?.output?.title || null;
  }

  const komentare = (await strankuj(api, `repos/${REPO}/issues/comments?sort=created&direction=desc&since=${new Date(od - OKNO).toISOString()}`,
    (dil) => Date.parse(dil[dil.length - 1].created_at) < od - OKNO))
    .map((k) => ({ cislo: Number(k.issue_url.split('/').pop()), autor: k.user?.login, telo: k.body || '', kdy: k.created_at }));

  const tyden = ted - 7 * DEN;
  const akce = {
    rozhodnuti: udalostiTydne.filter((u) => u.event === 'labeled' && ['schvaleno', 'zamitnuto', 'stop'].includes(u.label?.name)
      && u.actor?.login === vlastnik && Date.parse(u.created_at) >= tyden).length,
  };

  return { pulls, issues, rezimy, komentare, akce, navrhy };
}
