// Otázky vlastníkovi (#385): když se AI v issue ptá (CLAUDE.md, pravidlo 8), přidá štítek `otazka`. Workflow
// Otázka vlastníkovi pak pošle otázku do Telegramu (AI píše z účtu vlastníka, takže GitHub mu nic neoznámí)
// a po odpovědi štítek odebere. Odpověď je komentář vlastníka bez patičky AI, nebo komentář vlastníka či asistenta
// zadání s nadpisem „Odpověď vlastníka“ (zápis odpovědi z rozhovoru). Bez modelu.
//
//   UDALOST=stitek|komentar CISLO=<issue> node scripts/brana/otazka.mjs

import { pathToFileURL } from 'node:url';

// Bez závislostí (workflow neinstaluje node_modules): REST GitHubu přímo přes fetch.
const REPO = process.env.GITHUB_REPOSITORY || 'tangero/stredniskoly';
const vytvorApi = ({ token = process.env.GITHUB_TOKEN } = {}) => async (cesta, { method = 'GET' } = {}) => {
  const odp = await fetch(`https://api.github.com/${cesta}`, {
    method, headers: { authorization: `Bearer ${token}`, accept: 'application/vnd.github+json', 'x-github-api-version': '2022-11-28' },
  });
  if (!odp.ok) throw new Error(`${method} ${cesta}: ${odp.status}`);
  return odp.status === 204 ? null : odp.json();
};

export const STITEK = 'otazka';
const PATICKA_AI = /Generated by \[?Claude Code|Zapsal Claude Code|— Eduarda \(AI/i;
const ODPOVED = /^#{1,3}[ \t]*Odpověď vlastníka/im;
export const MAX_TEXT = 1500;

/** Komentář je odpověď na otázku: od vlastníka bez patičky AI, nebo od vlastníka či asistenta s nadpisem „Odpověď vlastníka“. */
export function jeOdpoved(k, { vlastnik, asistent }) {
  const telo = k.telo || '';
  if (k.autor === vlastnik && (ODPOVED.test(telo) || !PATICKA_AI.test(telo))) return true;
  return k.autor === asistent && ODPOVED.test(telo);
}

/** Text otázky: poslední komentář vlastníka nebo asistenta s patičkou AI, který není odpovědí; bez patičky, zkrácený. */
export function textOtazky(komentare, ucty) {
  const otazka = [...komentare].reverse().find((k) => [ucty.vlastnik, ucty.asistent].includes(k.autor)
    && PATICKA_AI.test(k.telo || '') && !ODPOVED.test(k.telo || ''));
  if (!otazka) return '';
  const t = otazka.telo.split(/\n-{3,}\s*\n/)[0].replace(/<!--[\s\S]*?-->/g, '').replace(/\*\*/g, '').replace(/`/g, '').trim();
  return t.length > MAX_TEXT ? `${t.slice(0, MAX_TEXT - 1)}…` : t;
}

export function zprava({ cislo, titulek, url, text }) {
  return `Otázka k #${cislo} ${titulek}\n\n${text || 'Text otázky je v issue.'}\n\nOdpověz komentářem v issue, nebo řekni Eduardě či Claude Code:\n${url}`;
}

async function posliTelegram(text) {
  const { TELEGRAM_BOT_TOKEN: bot, TELEGRAM_CHAT_ID: chat } = process.env;
  if (!bot || !chat) return console.log('Telegram není nastavený, otázku neposílám.');
  const odp = await fetch(`https://api.telegram.org/bot${bot}/sendMessage`, {
    method: 'POST', headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ chat_id: chat, text, disable_web_page_preview: true }),
  });
  if (!odp.ok) throw new Error(`Telegram: ${odp.status}`);
}

async function main() {
  const { UDALOST: udalost, CISLO: cislo, VLASTNIK: vlastnik, ASISTENT: asistent } = process.env;
  if (!/^\d+$/.test(cislo || '')) throw new Error('CISLO není číslo issue.');
  const ucty = { vlastnik, asistent };
  const api = vytvorApi();
  if (udalost === 'stitek') {
    if (![vlastnik, asistent].includes(process.env.AKTER)) return console.log(`Štítek přidal ${process.env.AKTER}, otázku neposílám.`);
    const issue = await api(`repos/${REPO}/issues/${cislo}`);
    const komentare = (await api(`repos/${REPO}/issues/${cislo}/comments?per_page=100`)).map((k) => ({ autor: k.user?.login, telo: k.body || '' }));
    const text = zprava({ cislo, titulek: issue.title, url: issue.html_url, text: textOtazky(komentare, ucty) });
    console.log(text);
    return posliTelegram(text);
  }
  if (udalost === 'komentar') {
    const k = { autor: process.env.KOMENTAR_AUTOR, telo: process.env.KOMENTAR_TELO || '' };
    if (!jeOdpoved(k, ucty)) return console.log('Komentář není odpovědí vlastníka, štítek zůstává.');
    // Token vlastníka (PROJECT_TOKEN), aby změna štítku spustila Tabuli.
    const zapis = vytvorApi({ token: process.env.STITKY_TOKEN || process.env.GITHUB_TOKEN });
    await zapis(`repos/${REPO}/issues/${cislo}/labels/${STITEK}`, { method: 'DELETE' }).catch((e) => {
      if (!/404/.test(e.message)) throw e;
    });
    return console.log(`Odpověď vlastníka: štítek ${STITEK} odebrán z #${cislo}.`);
  }
  throw new Error(`Neznámá událost ${udalost}.`);
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
