// Ověření na náhledu samostatným agentem (#333, docs/navrh-rizeni-vyvoje-2027.md, oddíl 11): kdo staví,
// ten neověřuje. Workflow overeni-nahledu.yml po nasazení náhledu PR předá ověřovateli jen kritéria K a P
// z uzavíraného zadání a adresu náhledu. Diff, popis PR ani komentáře nevidí. Protokol zapíše
// github-actions[bot]; brána ho uzná jako každý jiný protokol.
//
//   node scripts/brana/overeni-nahledu.mjs priprav                          (job „Příprava“, událost workflow_run)
//   node scripts/brana/overeni-nahledu.mjs zapis <pr> <sha> <náhled> <soubor> (job „Zápis“, výstup ověřovatele)
//
// Výsledek přípravy jde do GITHUB_OUTPUT. Konfiguraci čte z main přes API, jako brána.

import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
import { duveryhodny, rozbor, kriteriaZadani, chybejiciVProtokolu, uzaviranaIssues } from './brana.mjs';
import { REPO, vytvorApi, nactiKonfig, nactiPr } from './data.mjs';

export const KONTEXT_NAHLEDU = 'Náhled (Vercel)';
export const OVEROVATEL = 'Ověřovatel: samostatný agent bez diffu';
// Náhled smí vést jen na nasazení Vercelu: ověřovatel na něj posílá bypass ochrany náhledů.
const ADRESA_NAHLEDU = /^https:\/\/[a-z0-9-]+\.vercel\.app\/?$/;

/** Adresa náhledu ze stavů commitu: jen stav zapsaný workflow Testy (github-actions[bot]) na *.vercel.app. */
export function adresaNahledu(stavy = []) {
  const s = stavy.find((x) => x.context === KONTEXT_NAHLEDU && x.state === 'success' && x.creator?.login === 'github-actions[bot]');
  return s && ADRESA_NAHLEDU.test(s.target_url || '') ? s.target_url.replace(/\/$/, '') : null;
}
// Řádky, které do protokolu doplňuje workflow, ne ověřovatel: hlavička, commit, náhled, ověřovatel.
const VYHRAZENE = /Protokol z preview|^\s*(Commit|Náhled|Ověřovatel)\s*:/im;

/**
 * Má se náhled ověřit? Jen commit, který je hlavou otevřeného PR z tohoto repozitáře od vlastníka nebo
 * asistenta zadání, mění web a uzavírá zadání s kritérii K a P od téhož okruhu autorů.
 */
export function rozhodniOvereni({ beh, repo, pr, soubory, issues, konfig, nahled }) {
  const nic = (duvod) => ({ akce: 'nic', duvod });
  if (beh.event !== 'push') return nic(`běh Testy z události ${beh.event}, náhled nasazuje jen push`);
  if (beh.conclusion !== 'success') return nic(`Testy skončily ${beh.conclusion}`);
  if (beh.head_repository?.full_name !== repo) return nic('commit z jiného repozitáře');
  if (!pr) return nic('commit není hlavou otevřeného PR');
  if (pr.hlava.sha !== beh.head_sha) return nic('commit už není hlavou PR');
  if (!duveryhodny(pr.autor, konfig)) return nic(`PR od účtu ${pr.autor}`);
  if (rozbor(soubory, konfig).jenBezPreview) return nic('PR nemění web');
  if (!nahled) return nic('commit nemá adresu náhledu');
  const uzavirana = new Set(uzaviranaIssues(pr.telo));
  const issue = issues.find((i) => uzavirana.has(i.cislo) && duveryhodny(i.autor, konfig) && kriteriaZadani(i.telo).length);
  if (!issue) return nic('PR neuzavírá zadání s kritérii K a P od vlastníka nebo asistenta zadání');
  return { akce: 'overit', duvod: `zadání #${issue.cislo}`, issue: issue.cislo, kriteria: kriteriaZadani(issue.telo) };
}

/** Protokol z výstupu ověřovatele: workflow doplní hlavičku, commit a náhled, ověřovatel jen řádky. */
export function sestavProtokol({ sha, nahled, vystup, kriteria }) {
  const radky = (vystup || '').replace(/\r\n?/g, '\n').split('\n').filter((r) => !VYHRAZENE.test(r));
  const tabulka = radky.join('\n').trim();
  if (!tabulka) return { ok: false, duvod: 'ověřovatel nevrátil žádný výsledek' };
  const chybi = chybejiciVProtokolu(kriteria.map((k) => k.oznaceni), tabulka);
  if (chybi.length) return { ok: false, duvod: `ověřovatel neuvedl kritéria ${chybi.join(', ')}` };
  return {
    ok: true,
    telo: [
      '## Protokol z preview',
      '',
      `Commit: ${sha.slice(0, 7)}`,
      `Náhled: ${nahled}`,
      OVEROVATEL,
      '',
      tabulka,
      '',
      '---',
      '_Ověřil samostatný agent ve workflow „Ověření na náhledu“ (#333): znal jen kritéria zadání a adresu náhledu, diff ani popis PR neviděl._',
      '_Generated by [Claude Code](https://claude.ai/code)_',
    ].join('\n'),
  };
}

function vystup(hodnoty) {
  const radky = Object.entries(hodnoty).map(([k, v]) => `${k}=${String(v ?? '').replace(/\r?\n/g, ' ')}`);
  if (process.env.GITHUB_OUTPUT) fs.appendFileSync(process.env.GITHUB_OUTPUT, `${radky.join('\n')}\n`);
  console.log(radky.join('\n'));
}

async function priprav(api) {
  const beh = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8')).workflow_run;
  const sha = beh.head_sha;
  const otevrene = (await api(`repos/${REPO}/commits/${sha}/pulls`)).filter((p) => p.state === 'open' && p.head?.sha === sha);
  const vstup = otevrene.length === 1 ? await nactiPr(api, otevrene[0].number) : null;
  const stavy = await api(`repos/${REPO}/commits/${sha}/statuses?per_page=100`);
  const nahled = adresaNahledu(stavy);
  const r = rozhodniOvereni({
    beh, repo: REPO, pr: vstup?.pr || null, soubory: vstup?.soubory || [], issues: vstup?.issues || [],
    konfig: await nactiKonfig(api), nahled,
  });
  vystup({
    akce: r.akce, duvod: r.duvod, pr: vstup?.pr.cislo || '', sha, nahled: nahled || '',
    // Kritéria jako base64: víc řádků v GITHUB_OUTPUT bez rizika, že text ukončí oddělovač.
    kriteria: r.kriteria ? Buffer.from(r.kriteria.map((k) => `- ${k.text}`).join('\n')).toString('base64') : '',
  });
}

async function zapis(api, cislo, sha, nahled, soubor) {
  const p = await api(`repos/${REPO}/pulls/${cislo}`);
  if (p.head.sha !== sha) return console.log(`PR #${cislo} má novou hlavu ${p.head.sha.slice(0, 7)}, protokol k ${sha.slice(0, 7)} se nezapíše.`);
  const kriteria = kriteriaZadani(Buffer.from(process.env.KRITERIA || '', 'base64').toString('utf8'));
  const vysledek = fs.existsSync(soubor) ? fs.readFileSync(soubor, 'utf8') : '';
  const protokol = sestavProtokol({ sha, nahled, vystup: vysledek, kriteria });
  const telo = protokol.ok
    ? protokol.telo
    : `Ověření na náhledu pro commit ${sha.slice(0, 7)} se nedokončilo: ${protokol.duvod}. Protokol z náhledu napíše Claude Code ručně (záloha podle skillu overeni-preview).\n\n— workflow Ověření na náhledu`;
  await api(`repos/${REPO}/issues/${cislo}/comments`, { method: 'POST', body: { body: telo } });
  console.log(protokol.ok ? `Protokol zapsán do PR #${cislo}.` : `Ověření nedokončeno: ${protokol.duvod}`);
}

async function main() {
  const [prikaz, ...args] = process.argv.slice(2);
  const api = vytvorApi();
  if (prikaz === 'priprav') return priprav(api);
  if (prikaz === 'zapis') return zapis(api, Number(args[0]), args[1], args[2], args[3]);
  throw new Error('použití: overeni-nahledu.mjs priprav | zapis <pr> <sha> <náhled> <soubor>');
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
